// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oscm_server.proto

#include "oscm_server.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class GetParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetParam>
      _instance;
} _GetParam_default_instance_;
class GetReturnDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetReturn>
      _instance;
} _GetReturn_default_instance_;
class PutParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PutParam>
      _instance;
} _PutParam_default_instance_;
class PutReturnDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PutReturn>
      _instance;
} _PutReturn_default_instance_;
class DeleteParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeleteParam>
      _instance;
} _DeleteParam_default_instance_;
class DeleteReturnDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeleteReturn>
      _instance;
} _DeleteReturn_default_instance_;
namespace protobuf_oscm_5fserver_2eproto {
static void InitDefaultsGetParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_GetParam_default_instance_;
    new (ptr) ::GetParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GetParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetParam}, {}};

static void InitDefaultsGetReturn() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_GetReturn_default_instance_;
    new (ptr) ::GetReturn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GetReturn::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetReturn =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetReturn}, {}};

static void InitDefaultsPutParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PutParam_default_instance_;
    new (ptr) ::PutParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PutParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PutParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPutParam}, {}};

static void InitDefaultsPutReturn() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PutReturn_default_instance_;
    new (ptr) ::PutReturn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PutReturn::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PutReturn =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPutReturn}, {}};

static void InitDefaultsDeleteParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_DeleteParam_default_instance_;
    new (ptr) ::DeleteParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DeleteParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DeleteParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDeleteParam}, {}};

static void InitDefaultsDeleteReturn() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_DeleteReturn_default_instance_;
    new (ptr) ::DeleteReturn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DeleteReturn::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DeleteReturn =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDeleteReturn}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetReturn.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PutParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PutReturn.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeleteParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeleteReturn.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetParam, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetReturn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetReturn, exists_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetReturn, blockid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetReturn, offset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GetReturn, size_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PutParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PutParam, blockid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PutParam, blockinfo_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PutReturn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DeleteParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DeleteParam, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DeleteReturn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::GetParam)},
  { 6, -1, sizeof(::GetReturn)},
  { 15, -1, sizeof(::PutParam)},
  { 22, -1, sizeof(::PutReturn)},
  { 27, -1, sizeof(::DeleteParam)},
  { 33, -1, sizeof(::DeleteReturn)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_GetParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_GetReturn_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PutParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PutReturn_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_DeleteParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_DeleteReturn_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "oscm_server.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021oscm_server.proto\"\027\n\010GetParam\022\013\n\003key\030\001"
      " \001(\t\"J\n\tGetReturn\022\016\n\006exists\030\001 \001(\010\022\017\n\007blo"
      "ckId\030\002 \001(\t\022\016\n\006offset\030\003 \001(\005\022\014\n\004size\030\004 \001(\005"
      "\".\n\010PutParam\022\017\n\007blockId\030\001 \001(\t\022\021\n\tblockIn"
      "fo\030\002 \001(\t\"\013\n\tPutReturn\"\032\n\013DeleteParam\022\013\n\003"
      "key\030\001 \001(\t\"\016\n\014DeleteReturn2\222\001\n\017MetadataSe"
      "rvice\022&\n\013GetMetadata\022\t.GetParam\032\n.GetRet"
      "urn\"\000\022&\n\013PutMetadata\022\t.PutParam\032\n.PutRet"
      "urn\"\000\022/\n\016DeleteMetadata\022\014.DeleteParam\032\r."
      "DeleteReturn\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 382);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "oscm_server.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_oscm_5fserver_2eproto

// ===================================================================

void GetParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetParam::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetParam::GetParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_GetParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GetParam)
}
GetParam::GetParam(const GetParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:GetParam)
}

void GetParam::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetParam::~GetParam() {
  // @@protoc_insertion_point(destructor:GetParam)
  SharedDtor();
}

void GetParam::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetParam::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetParam& GetParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_GetParam.base);
  return *internal_default_instance();
}


void GetParam::Clear() {
// @@protoc_insertion_point(message_clear_start:GetParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GetParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GetParam.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GetParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GetParam)
  return false;
#undef DO_
}

void GetParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GetParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GetParam.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GetParam)
}

::google::protobuf::uint8* GetParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GetParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GetParam.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetParam)
  return target;
}

size_t GetParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GetParam)
  GOOGLE_DCHECK_NE(&from, this);
  const GetParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GetParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GetParam)
    MergeFrom(*source);
  }
}

void GetParam::MergeFrom(const GetParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GetParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void GetParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GetParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetParam::CopyFrom(const GetParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetParam::IsInitialized() const {
  return true;
}

void GetParam::Swap(GetParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetParam::InternalSwap(GetParam* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetParam::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetReturn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetReturn::kExistsFieldNumber;
const int GetReturn::kBlockIdFieldNumber;
const int GetReturn::kOffsetFieldNumber;
const int GetReturn::kSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetReturn::GetReturn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_GetReturn.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:GetReturn)
}
GetReturn::GetReturn(const GetReturn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  blockid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.blockid().size() > 0) {
    blockid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockid_);
  }
  ::memcpy(&exists_, &from.exists_,
    static_cast<size_t>(reinterpret_cast<char*>(&size_) -
    reinterpret_cast<char*>(&exists_)) + sizeof(size_));
  // @@protoc_insertion_point(copy_constructor:GetReturn)
}

void GetReturn::SharedCtor() {
  blockid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&exists_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&size_) -
      reinterpret_cast<char*>(&exists_)) + sizeof(size_));
}

GetReturn::~GetReturn() {
  // @@protoc_insertion_point(destructor:GetReturn)
  SharedDtor();
}

void GetReturn::SharedDtor() {
  blockid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetReturn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetReturn::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetReturn& GetReturn::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_GetReturn.base);
  return *internal_default_instance();
}


void GetReturn::Clear() {
// @@protoc_insertion_point(message_clear_start:GetReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blockid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&exists_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&size_) -
      reinterpret_cast<char*>(&exists_)) + sizeof(size_));
  _internal_metadata_.Clear();
}

bool GetReturn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GetReturn)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool exists = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &exists_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string blockId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_blockid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->blockid().data(), static_cast<int>(this->blockid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GetReturn.blockId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 offset = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &offset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GetReturn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GetReturn)
  return false;
#undef DO_
}

void GetReturn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GetReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool exists = 1;
  if (this->exists() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->exists(), output);
  }

  // string blockId = 2;
  if (this->blockid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockid().data(), static_cast<int>(this->blockid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GetReturn.blockId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->blockid(), output);
  }

  // int32 offset = 3;
  if (this->offset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->offset(), output);
  }

  // int32 size = 4;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GetReturn)
}

::google::protobuf::uint8* GetReturn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GetReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool exists = 1;
  if (this->exists() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->exists(), target);
  }

  // string blockId = 2;
  if (this->blockid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockid().data(), static_cast<int>(this->blockid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GetReturn.blockId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->blockid(), target);
  }

  // int32 offset = 3;
  if (this->offset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->offset(), target);
  }

  // int32 size = 4;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->size(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetReturn)
  return target;
}

size_t GetReturn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetReturn)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string blockId = 2;
  if (this->blockid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->blockid());
  }

  // bool exists = 1;
  if (this->exists() != 0) {
    total_size += 1 + 1;
  }

  // int32 offset = 3;
  if (this->offset() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->offset());
  }

  // int32 size = 4;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetReturn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GetReturn)
  GOOGLE_DCHECK_NE(&from, this);
  const GetReturn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetReturn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GetReturn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GetReturn)
    MergeFrom(*source);
  }
}

void GetReturn::MergeFrom(const GetReturn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GetReturn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.blockid().size() > 0) {

    blockid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockid_);
  }
  if (from.exists() != 0) {
    set_exists(from.exists());
  }
  if (from.offset() != 0) {
    set_offset(from.offset());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
}

void GetReturn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GetReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetReturn::CopyFrom(const GetReturn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetReturn::IsInitialized() const {
  return true;
}

void GetReturn::Swap(GetReturn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetReturn::InternalSwap(GetReturn* other) {
  using std::swap;
  blockid_.Swap(&other->blockid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(exists_, other->exists_);
  swap(offset_, other->offset_);
  swap(size_, other->size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetReturn::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PutParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PutParam::kBlockIdFieldNumber;
const int PutParam::kBlockInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PutParam::PutParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_PutParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PutParam)
}
PutParam::PutParam(const PutParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  blockid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.blockid().size() > 0) {
    blockid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockid_);
  }
  blockinfo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.blockinfo().size() > 0) {
    blockinfo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:PutParam)
}

void PutParam::SharedCtor() {
  blockid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blockinfo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PutParam::~PutParam() {
  // @@protoc_insertion_point(destructor:PutParam)
  SharedDtor();
}

void PutParam::SharedDtor() {
  blockid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blockinfo_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PutParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PutParam::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PutParam& PutParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_PutParam.base);
  return *internal_default_instance();
}


void PutParam::Clear() {
// @@protoc_insertion_point(message_clear_start:PutParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blockid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blockinfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool PutParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PutParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string blockId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_blockid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->blockid().data(), static_cast<int>(this->blockid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PutParam.blockId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string blockInfo = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_blockinfo()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->blockinfo().data(), static_cast<int>(this->blockinfo().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PutParam.blockInfo"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PutParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PutParam)
  return false;
#undef DO_
}

void PutParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PutParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string blockId = 1;
  if (this->blockid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockid().data(), static_cast<int>(this->blockid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PutParam.blockId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->blockid(), output);
  }

  // string blockInfo = 2;
  if (this->blockinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockinfo().data(), static_cast<int>(this->blockinfo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PutParam.blockInfo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->blockinfo(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PutParam)
}

::google::protobuf::uint8* PutParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PutParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string blockId = 1;
  if (this->blockid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockid().data(), static_cast<int>(this->blockid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PutParam.blockId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->blockid(), target);
  }

  // string blockInfo = 2;
  if (this->blockinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blockinfo().data(), static_cast<int>(this->blockinfo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PutParam.blockInfo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->blockinfo(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PutParam)
  return target;
}

size_t PutParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PutParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string blockId = 1;
  if (this->blockid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->blockid());
  }

  // string blockInfo = 2;
  if (this->blockinfo().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->blockinfo());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PutParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PutParam)
  GOOGLE_DCHECK_NE(&from, this);
  const PutParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PutParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PutParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PutParam)
    MergeFrom(*source);
  }
}

void PutParam::MergeFrom(const PutParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PutParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.blockid().size() > 0) {

    blockid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockid_);
  }
  if (from.blockinfo().size() > 0) {

    blockinfo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blockinfo_);
  }
}

void PutParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PutParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PutParam::CopyFrom(const PutParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PutParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PutParam::IsInitialized() const {
  return true;
}

void PutParam::Swap(PutParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PutParam::InternalSwap(PutParam* other) {
  using std::swap;
  blockid_.Swap(&other->blockid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  blockinfo_.Swap(&other->blockinfo_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PutParam::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PutReturn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PutReturn::PutReturn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_PutReturn.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PutReturn)
}
PutReturn::PutReturn(const PutReturn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PutReturn)
}

void PutReturn::SharedCtor() {
}

PutReturn::~PutReturn() {
  // @@protoc_insertion_point(destructor:PutReturn)
  SharedDtor();
}

void PutReturn::SharedDtor() {
}

void PutReturn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PutReturn::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PutReturn& PutReturn::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_PutReturn.base);
  return *internal_default_instance();
}


void PutReturn::Clear() {
// @@protoc_insertion_point(message_clear_start:PutReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool PutReturn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PutReturn)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:PutReturn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PutReturn)
  return false;
#undef DO_
}

void PutReturn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PutReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PutReturn)
}

::google::protobuf::uint8* PutReturn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PutReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PutReturn)
  return target;
}

size_t PutReturn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PutReturn)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PutReturn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PutReturn)
  GOOGLE_DCHECK_NE(&from, this);
  const PutReturn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PutReturn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PutReturn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PutReturn)
    MergeFrom(*source);
  }
}

void PutReturn::MergeFrom(const PutReturn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PutReturn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void PutReturn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PutReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PutReturn::CopyFrom(const PutReturn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PutReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PutReturn::IsInitialized() const {
  return true;
}

void PutReturn::Swap(PutReturn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PutReturn::InternalSwap(PutReturn* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PutReturn::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DeleteParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeleteParam::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeleteParam::DeleteParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_DeleteParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DeleteParam)
}
DeleteParam::DeleteParam(const DeleteParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:DeleteParam)
}

void DeleteParam::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DeleteParam::~DeleteParam() {
  // @@protoc_insertion_point(destructor:DeleteParam)
  SharedDtor();
}

void DeleteParam::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DeleteParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DeleteParam::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeleteParam& DeleteParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_DeleteParam.base);
  return *internal_default_instance();
}


void DeleteParam::Clear() {
// @@protoc_insertion_point(message_clear_start:DeleteParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool DeleteParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DeleteParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DeleteParam.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DeleteParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DeleteParam)
  return false;
#undef DO_
}

void DeleteParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DeleteParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeleteParam.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DeleteParam)
}

::google::protobuf::uint8* DeleteParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DeleteParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeleteParam.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DeleteParam)
  return target;
}

size_t DeleteParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DeleteParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeleteParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DeleteParam)
  GOOGLE_DCHECK_NE(&from, this);
  const DeleteParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DeleteParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DeleteParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DeleteParam)
    MergeFrom(*source);
  }
}

void DeleteParam::MergeFrom(const DeleteParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DeleteParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void DeleteParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DeleteParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeleteParam::CopyFrom(const DeleteParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DeleteParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteParam::IsInitialized() const {
  return true;
}

void DeleteParam::Swap(DeleteParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeleteParam::InternalSwap(DeleteParam* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DeleteParam::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DeleteReturn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeleteReturn::DeleteReturn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oscm_5fserver_2eproto::scc_info_DeleteReturn.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DeleteReturn)
}
DeleteReturn::DeleteReturn(const DeleteReturn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DeleteReturn)
}

void DeleteReturn::SharedCtor() {
}

DeleteReturn::~DeleteReturn() {
  // @@protoc_insertion_point(destructor:DeleteReturn)
  SharedDtor();
}

void DeleteReturn::SharedDtor() {
}

void DeleteReturn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DeleteReturn::descriptor() {
  ::protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeleteReturn& DeleteReturn::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oscm_5fserver_2eproto::scc_info_DeleteReturn.base);
  return *internal_default_instance();
}


void DeleteReturn::Clear() {
// @@protoc_insertion_point(message_clear_start:DeleteReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool DeleteReturn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DeleteReturn)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:DeleteReturn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DeleteReturn)
  return false;
#undef DO_
}

void DeleteReturn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DeleteReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DeleteReturn)
}

::google::protobuf::uint8* DeleteReturn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DeleteReturn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DeleteReturn)
  return target;
}

size_t DeleteReturn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DeleteReturn)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeleteReturn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DeleteReturn)
  GOOGLE_DCHECK_NE(&from, this);
  const DeleteReturn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DeleteReturn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DeleteReturn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DeleteReturn)
    MergeFrom(*source);
  }
}

void DeleteReturn::MergeFrom(const DeleteReturn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DeleteReturn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void DeleteReturn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DeleteReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeleteReturn::CopyFrom(const DeleteReturn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DeleteReturn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteReturn::IsInitialized() const {
  return true;
}

void DeleteReturn::Swap(DeleteReturn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeleteReturn::InternalSwap(DeleteReturn* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DeleteReturn::GetMetadata() const {
  protobuf_oscm_5fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oscm_5fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GetParam* Arena::CreateMaybeMessage< ::GetParam >(Arena* arena) {
  return Arena::CreateInternal< ::GetParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::GetReturn* Arena::CreateMaybeMessage< ::GetReturn >(Arena* arena) {
  return Arena::CreateInternal< ::GetReturn >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PutParam* Arena::CreateMaybeMessage< ::PutParam >(Arena* arena) {
  return Arena::CreateInternal< ::PutParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PutReturn* Arena::CreateMaybeMessage< ::PutReturn >(Arena* arena) {
  return Arena::CreateInternal< ::PutReturn >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DeleteParam* Arena::CreateMaybeMessage< ::DeleteParam >(Arena* arena) {
  return Arena::CreateInternal< ::DeleteParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DeleteReturn* Arena::CreateMaybeMessage< ::DeleteReturn >(Arena* arena) {
  return Arena::CreateInternal< ::DeleteReturn >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
